dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "6"
cache:
  yarn: true
before_script:
  - truffle version
  - yarn list
  - yarn lint
  - yarn testrpc &
  - sleep 1
script:
  - yarn test
#   - yarn coverage
