linkPrefix = ""
name = "wyvern-ethereum"
license = "MIT"
version = "1.0.0"
description = "Wyvern Ethereum Contracts"
homepage = "https://github.com/protinam/wyvern-ethereum#readme"
author = "Project Wyvern Developers"
buildTime = 2017-11-25T01:11:18.806Z
target = "doxity"
src = "contracts/*"
dir = "pages/docs"
out = "docs"

[interaction]