linkPrefix = ""
name = "wyvern-ethereum"
license = "MIT"
version = "1.0.0"
description = "Wyvern Ethereum Contracts"
homepage = "https://github.com/ProjectWyvern/wyvern-ethereum#readme"
author = "Project Wyvern Developers"
buildTime = 2018-02-02T08:10:56.948Z
target = "doxity"
src = "contracts/*"
dir = "pages/docs"
out = "docs"

[interaction]